hash-format = "sha256"

[[files]]
file = "mods/advanced-peripherals.pw.toml"
hash = "7d0eaa4dcbca122712fffb4cd8b02450d0b7bf9d0e08899bb82967a4471dc3b6"
metafile = true

[[files]]
file = "mods/ae2-things-forge.pw.toml"
hash = "b3d0b1ae9fe6c20a0d6be1de971046d7747e1534c8a8b728eb6ebc1ccbfc7412"
metafile = true

[[files]]
file = "mods/ai-improvements.pw.toml"
hash = "7625fd02a8edcfaf66ae149456ba29e237a4740b6f2540fd2886a0ecaca189b7"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "d83fccfbefa34aae187e64c16dd91a4416a276de4603397a94b2706ccc2667a8"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1be3c626f8c8e445e57444f2559dc590edafc75b6c8c18d4599703dbc614a7e8"
metafile = true

[[files]]
file = "mods/applied-energistics-2-wireless-terminals.pw.toml"
hash = "cdc65d49eb4a1ebdffdab6eefa5c3ed90b1e32016a45b894a5cc431c109b7e3b"
metafile = true

[[files]]
file = "mods/applied-energistics-2.pw.toml"
hash = "ff29316754f5561868f2fde142e4625b14b2130ac6073af78ee9449c4e2fc13b"
metafile = true

[[files]]
file = "mods/applied-mekanistics.pw.toml"
hash = "3761680fb5aecd99a6ad070c4b8387157aab76962e90cf4f81aa864898acd87e"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "e81baa549b913cf7d30a730d18846ff41aa833928328e3e1f2ec0686d815cd47"
metafile = true

[[files]]
file = "mods/attributefix.pw.toml"
hash = "a5823eed363dcbf221b6d0e919b111f0a5676338967a2a599c7cb948ca24223d"
metafile = true

[[files]]
file = "mods/autoreglib.pw.toml"
hash = "93e1dd0ac54ad216cf4ee82e5ab12a7de23d7cdfe7a27eb0b0c168a1c939db4a"
metafile = true

[[files]]
file = "mods/bookshelf.pw.toml"
hash = "3094a52897889217e37bf772fa43727fc4a7f81d0dc9a5e25be933630192bcbb"
metafile = true

[[files]]
file = "mods/catalogue.pw.toml"
hash = "f123a2b4bae7be86d7bc6c4f6cfb30d914991558cd744b3b3c561088848ae416"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "d9a854dc615bafee94247c2ad9e9d794f291c37cd03b61b9323222ad4a4a96e5"
metafile = true

[[files]]
file = "mods/cccbridge.pw.toml"
hash = "99b055a561787707364958cba2b5d4183130fd4d76b778469e4b69621d0ce066"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "6246a75881b9a8d7cd424b5f94af842a7eaa2f676c2042712fdfd95e89914d96"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "2053b64e0f1507f2a8c485c57530718a614a53f24a4d0e348975b3127a42753f"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "2c3ddac643593c3dec5bdad4a4ee6d10b62430409ee1c558ce3c5cbed9f40700"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "5880c81df1af395ec3762eff4e98c78f7b75e62db67e1d191a1772d79aabc073"
metafile = true

[[files]]
file = "mods/codechicken-lib-1-8.pw.toml"
hash = "79d38d4c976dadf89d2fd2978a0af50894ae0373fd784fecb369e47beda145bf"
metafile = true

[[files]]
file = "mods/cofh-core.pw.toml"
hash = "09796a48f3857c1f41280849c100baff40631035f64e79d494b2a0538a7676fb"
metafile = true

[[files]]
file = "mods/configured.pw.toml"
hash = "767d7abb22c9ac0b9e300d35685847ff27aa1a942cd857fac31fe532683c2437"
metafile = true

[[files]]
file = "mods/connectivity.pw.toml"
hash = "d2493cda0721ddca80f37aff224e0291256176c6b940a06268fdd3eef45b92a1"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "a94bec93c6e2f350d4bfd94d6f557fca51ef4358aa4a714e87816243537a6623"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.pw.toml"
hash = "c98b92c96eb546872a0d203969ddba29a17f6ab0e57ff93081d81a138562e8b7"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "d1ca7062b1b570fcaa7510f0bb53ce1c0904b19d2502b20aaddd55555367351f"
metafile = true

[[files]]
file = "mods/create-track-map.pw.toml"
hash = "fd2f4e87da02c7accef457d307669a303991f16dc1ca115f30c99677ff409c6f"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "e383476cde5d88b8f24936f1030defde1b202e6eedd52e078169f19fc7735c7c"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "0c96d11ee0a334fc444a623848602afd153a2180aeac80b8f0ed01ca72ba7c0b"
metafile = true

[[files]]
file = "mods/ctm.pw.toml"
hash = "fc5f6ed8b94d805cc915c961b75afb8dbf8bd04cd7d0e2efaa1c58e6a2085aef"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "164205fa6e64cbe27b2b383698cd2f9d42ff1b19ed820b95eb72e7d7eeadfde7"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "fdeab9633fc995e4910a08d6d8110a258f30b37c7a65128b8d6a46af797df3a0"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "844c67461a97a2c8da327034806444c66579bc0fc118f0b9a0abe225d77ed7ce"
metafile = true

[[files]]
file = "mods/ender-storage-1-8.pw.toml"
hash = "b8ba0a251d14abf255a8477337c2d81023228c779793218ef3990247632ef86e"
metafile = true

[[files]]
file = "mods/falling-tree.pw.toml"
hash = "e6f923a462483ca6233b7860d88952594417afa578196d690b7112339f469a6c"
metafile = true

[[files]]
file = "mods/fastfurnace.pw.toml"
hash = "e001ea41a138e42e5523e69b13523c1ebf76a1633320b3a7942b4eef76d36861"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
hash = "534a07d970cbf69e74b872218550a94fe062060e3e2c001b2c37d7c973787a07"
metafile = true

[[files]]
file = "mods/fastworkbench.pw.toml"
hash = "fb43a2bb5fc3c56a05fc8ae902610e5f7ab46f62e58d50b1ec34390ce5698335"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "550b3de3b381de59621254f85bafc29ce4986e4277956e5b1cca98b0e8cff06c"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "3dd1936c1d9158575cd479b928fcdc01508c6b241d29bc57943befe0d751ec93"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "919987a18eca78288796a47c577cb7762771de8bb221e3f35fdc70f9b823825f"
metafile = true

[[files]]
file = "mods/iron-chests.pw.toml"
hash = "755a8345636199e68830426bb03873a2395517d719c82dfb9a349d09fe970ea9"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "7d4ed176565a8ba1d45289734e5aef2343c726c307cf06022ac1b21ebe5a3e2d"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "34beff832b98f209ac50078a6901688c2f1318739c3ebb242ee31d00e2409d3a"
metafile = true

[[files]]
file = "mods/just-enough-professions-jep.pw.toml"
hash = "413806f003b9c9b62f701d97aaf128534618d25c3fda27505e1543b44fe20f79"
metafile = true

[[files]]
file = "mods/just-enough-resources-jer.pw.toml"
hash = "224dc68333b17b52fbb9e2b69bf67c1b919fcac1125d9bbeae8c8c6613766bfa"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "94d853ec0def62adb527aee046f2c4a32127076c2995ea5c29553534544e1c35"
metafile = true

[[files]]
file = "mods/krypton-reforged.pw.toml"
hash = "ce783b1cef4c49c9a8572ceca99812e9b6ed980410a335d66ed5b761645708be"
metafile = true

[[files]]
file = "mods/lazy-dfu-forge.pw.toml"
hash = "4197e21b90ffc991b42fb07a8e2c55824ba30f66185688a1e63ddbbecd10937e"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "b5292abed469471b736d2b9f47b21d861e9b6cbf332a225e781bb47aca40d3a3"
metafile = true

[[files]]
file = "mods/markdownmanual.pw.toml"
hash = "409d32841ac9cfda6ff7d5d78eb2717f3ddf789f3773cab39b056574c2e3ec31"
metafile = true

[[files]]
file = "mods/mekanism-additions.pw.toml"
hash = "4a3bba5ee25abee71e11f41208f0ae7f09d48dbd43099b52ef1750532d0247fe"
metafile = true

[[files]]
file = "mods/mekanism-generators.pw.toml"
hash = "0a6a0129d354bbf733d4adb7efd39c6646f790827d76ae3a2e25cc855bdecd4d"
metafile = true

[[files]]
file = "mods/mekanism-tools.pw.toml"
hash = "5ceee998d53af5f7bc5b20b48a695d4e2f19fa60af701376f3e34f6a271c62d9"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
hash = "36b3da73d8ce3dfaa5c9a5dae7db10df3ee25f0d32cff6e1cde5407c5e6f271f"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ad64853eb5ba56dc6e4b1bb9214dbfe28e2a0c865dc76b4b77edee0f11adceff"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "be808b0e427ee7855a826df95893b3fe3f3cebff45fb47d89ad2bcc85932af4f"
metafile = true

[[files]]
file = "mods/more-red-x-cc-tweaked-compat.pw.toml"
hash = "c8a5b96df890c2a7c3fce413ea7a90447aefc29ea1246d41e5aa07ea2ec2bc31"
metafile = true

[[files]]
file = "mods/more-red.pw.toml"
hash = "8e17e82afa8b664f2f1dabbe72fcd172d14e5a431e67a0c0053d617c0560a8de"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6c5e1d646bee1575bd994996b4428e0fe16c6a0bfc0fbab5c6fa0c8c35547863"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "ebe4f9026b88b5e526c15cfb5a00f78b3c7538970df343803fbcdf36ede37534"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "f3eeeb3eed7d37447078f64e58cca79628e460f7666f33be40ea30587ebefb2b"
metafile = true

[[files]]
file = "mods/overloaded-armor-bar.pw.toml"
hash = "a793e307448377f212ceeec69f47cc56a61695a56a81e59509c269b4d5c47562"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "e0cbe5dbdbece52f9471e318cabec09569b95c35ed72e568b015e2d9c5d3c9dc"
metafile = true

[[files]]
file = "mods/placebo.pw.toml"
hash = "45e43a9de14a5e70bc6cede52536235ffeacc5057f1744c1e0f80d1bb3f0fa0a"
metafile = true

[[files]]
file = "mods/plasmo-voice.pw.toml"
hash = "ec3a739d407c00f054e498865df68d204ac861783e687f4e2313b25f4b0f5e20"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "b004022582a154f5d55c1b7660a4075f37962783dc20af8f046afe3bbc839171"
metafile = true

[[files]]
file = "mods/quark.pw.toml"
hash = "ff6742aace7a51c492d8ec2025103d4627d2b157efba5902ba8a8f4bb7e6b14c"
metafile = true

[[files]]
file = "mods/reauth.pw.toml"
hash = "da46985b92972295e91b1a3365b79fdd526ce3f7000c56e4975fa63112f57837"
metafile = true

[[files]]
file = "mods/rechiseled.pw.toml"
hash = "f4c38fff3ef849574666c3fd89664e76b9ac92dfe15c0d3a0d7522c88acbc42a"
metafile = true

[[files]]
file = "mods/redstone-arsenal.pw.toml"
hash = "da033275ed1c01c6b67a07951db97bed4742600be79b6056bc0412c59d95cba6"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "7089cdcaf2c1f1b9f6a9a28195c6925cda1af4dce16fd9f6f241d6340d5c8911"
metafile = true

[[files]]
file = "mods/rubidium.pw.toml"
hash = "8def45a48d62b220050f5b7c290dda439c71bdb1e30120f63eb15242b7e4517c"
metafile = true

[[files]]
file = "mods/simple-backups.pw.toml"
hash = "0f1b9970b4dddf8ff69a778c25dcadda8e91e0305c26581ebb7c1d7f54c3b7f9"
metafile = true

[[files]]
file = "mods/smooth-chunk-save.pw.toml"
hash = "567d43f70efd22845aa0ad791dac01e6d14ea58c8bb0e9a99246f904e7cf73aa"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "64d6d2b4b9b9960013ee67b62bfee64daec02d957b1689c783a1ea01c24d445a"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "6d00f58cff712ec72a8ae7a682faf73777cf9e37c2b73bf0ed57ebe55312da0b"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "555c2ed7500d7deb9f0dbfbc6a597bfa76ae2a22ccdbe7ab3632cde4278169b4"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "1f20786408ae526f5df6a6cde7c04c4dd4afc2d87d5bc24a109687622f9db356"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "54d63280847c1aeda342100d55fc63cbfcf9732c24f1e0cda325bc7216aadc05"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "1ab6b34e42b6bc8c2f801e306de0957de2f0f964734acdc11cfa7dd1c82b55a0"
metafile = true

[[files]]
file = "mods/thermal-cultivation.pw.toml"
hash = "efe4e5faaa2654b43eab5a52ceb53c2e1a85e26fc472873240d1cb643628a1ca"
metafile = true

[[files]]
file = "mods/thermal-dynamics.pw.toml"
hash = "046ac30bb218b0e300fbf9e3e817c386edb29ce761210842bd85c0293935fe49"
metafile = true

[[files]]
file = "mods/thermal-expansion.pw.toml"
hash = "1674bdf60e7e343ccdfb66489f8880912f68207ef4e8ab51fd814e40cef157ad"
metafile = true

[[files]]
file = "mods/thermal-foundation.pw.toml"
hash = "e620d8a97266e15bf3f2009ee60ef74c39ba6d20172026d90e1470c5e5929ce5"
metafile = true

[[files]]
file = "mods/thermal-innovation.pw.toml"
hash = "38d56b7239c363af2bc57d44c365256c1ed8ec8bf7c55610352fab21dfbaa4d1"
metafile = true

[[files]]
file = "mods/thermal-integration.pw.toml"
hash = "b7405d5625b7967e6a950647f9a77cb26b909827e7cb1cdd4927d2c3d007b5a5"
metafile = true

[[files]]
file = "mods/thermal-locomotion.pw.toml"
hash = "c4fd78c629d2a66713a7fb8505ca5dabaf73d14e50adf6ff5edebd5d81a92ca7"
metafile = true

[[files]]
file = "mods/tis-3d.pw.toml"
hash = "4e8e53fc3f76ec00e43c5fe8d4e98682662880fec43fbe8f838c9051eaa68973"
metafile = true

[[files]]
file = "mods/tis-create.pw.toml"
hash = "8a270d999c8aefa6ca3ad06d5ad6a8b68cf2d9887f4352de5ced797b2cd97a41"
metafile = true

[[files]]
file = "mods/toast-control.pw.toml"
hash = "8ff48d18f2fbe8df674dcd79aabcece27808667c270401b06ac10c97d7552990"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "4bc45052af6997d245483069aad79225260be1773e6a578643f16773791ecfb3"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "ad2916b2d26a7a3a255e889d0032e5539005dc3ee6abebc46a22f93655f549f8"
metafile = true
